-- 1. Create the profiles table
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT,
  name TEXT,
  age INTEGER,
  gender TEXT,
  blood_group TEXT,
  emergency_contact TEXT,
  allergies TEXT,
  photo_url TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- 3. Create RLS Policies
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles
  FOR SELECT USING (true);

CREATE POLICY "Users can insert their own profile." ON public.profiles
  FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile." ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

-- 4. (Strongly Recommended) Create a trigger to handle new user signup
-- This ensures the profile is created even if the client-side insert fails
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, name)
  VALUES (new.id, new.email, new.raw_user_meta_data->>'name');
  RETURN new;
EXCEPTION WHEN OTHERS THEN
  RAISE EXCEPTION 'Database error saving new user';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Redefine the trigger
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 5. Create medical_records table
CREATE TABLE IF NOT EXISTS public.medical_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  date DATE NOT NULL,
  diagnosis TEXT NOT NULL,
  treatment TEXT NOT NULL,
  doctor TEXT,
  notes TEXT,
  prescription_url TEXT,
  body_part TEXT,
  priority TEXT CHECK (priority IN ('Low', 'High')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Create vitals table
CREATE TABLE IF NOT EXISTS public.vitals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  date DATE NOT NULL,
  bp TEXT,
  sugar INTEGER,
  temperature TEXT,
  report_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Enable RLS for new tables
ALTER TABLE public.medical_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vitals ENABLE ROW LEVEL SECURITY;

-- 8. RLS Policies for medical_records
CREATE POLICY "Users can view own medical records." ON public.medical_records
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own medical records." ON public.medical_records
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own medical records." ON public.medical_records
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own medical records." ON public.medical_records
  FOR DELETE USING (auth.uid() = user_id);

-- 9. RLS Policies for vitals
CREATE POLICY "Users can view own vitals." ON public.vitals
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own vitals." ON public.vitals
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own vitals." ON public.vitals
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own vitals." ON public.vitals
  FOR DELETE USING (auth.uid() = user_id);

